const GET_COINLIST_REQUEST = 'GET_COINLIST_REQUEST';
const GET_COINLIST_SUCCESS = 'GET_COINLIST_SUCCESS';
const GET_COINLIST_FAILURE = 'GET_COINLIST_FAILURE';
const GET_MORE_COINLIST = 'GET_MORE_COINLIST';
const GET_MORE_ENDED = 'LOAD_MORE_ENDED';

export { GET_COINLIST_REQUEST, GET_COINLIST_SUCCESS, GET_COINLIST_FAILURE, GET_MORE_COINLIST, GET_MORE_ENDED };
